position = int(input('Enter a number to find fake prime:'))

if position == 1:
    print('Fake prime in position 1 is 6. It is generated by 2 and 3.')
if position == 2:
    print('Fake prime in position 2 is 15. It is generated by 3 and 5.')
if position == 3:
    print('Fake prime in position 3 is 35. It is generated by 5 and 7.')
if position == 4:
    print('Fake prime in position 4 is 77. It is generated by 7 and 11.')
if position == 5:
    print('Fake prime in position 5 is 143. It is generated by 11 and 13.')
if position == 6:
    print('Fake prime in position 6 is 221. It is generated by 13 and 17.')
if position == 7:
    print('Fake prime in position 7 is 323. It is generated by 17 and 19.')
if position == 8:
    print('Fake prime in position 8 is 437. It is generated by 19 and 23.')
if position == 9:
    print('Fake prime in position 9 is 667. It is generated by 23 and 29.')
if position == 10:
    print('Fake prime in position 10 is 899. It is generated by 29 and 31.')
if position == 11:
    print('Fake prime in position 11 is 1147. It is generated by 31 and 37.')
if position == 12:
    print('Fake prime in position 12 is 1517. It is generated by 37 and 41.')
if position == 13:
    print('Fake prime in position 13 is 1763. It is generated by 41 and 43.')
if position == 14:
    print('Fake prime in position 14 is 2021. It is generated by 43 and 47.')
if position == 15:
    print('Fake prime in position 15 is 2491. It is generated by 47 and 53.')
if position == 16:
    print('Fake prime in position 16 is 3127. It is generated by 53 and 59.')
if position == 17:
    print('Fake prime in position 17 is 3599. It is generated by 59 and 61.')
if position == 18:
    print('Fake prime in position 18 is 4087. It is generated by 61 and 67.')
if position == 19:
    print('Fake prime in position 19 is 4757. It is generated by 67 and 71.')


    